version: '3'
services:
  scrapy-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/output
      - ./scrapy_test:/app/scrapy_test
    command: ["sh", "-c", "scrapy crawl website -a urls_file=urls.txt && cp /app/output.json /output/output.json"]
