version: '3'
services:
  scrapy-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/output
      - ./scrapy_test:/app/scrapy_test
    command: ["scrapy", "crawl", "website", "-a", "urls_file=urls.txt"]
